apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourceapi
  namespace: citizendemo
  labels:
    app: resourceapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resourceapi
  strategy: 
    type: Recreate
  template:
    metadata:
      name: resourceapi
      namespace: citizendemo
      labels:
        app: resourceapi
    spec:
      containers:
        - name: resourceapi
          image: citizendemoacreastus.azurecr.io/citizendemo/resourceapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: resourceapi
  namespace: citizendemo
  labels:
    app: resourceapi
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: resourceapi
